-- Migration 012: Poll participants table for unique vote enforcement
-- NOTE: This file reflects the schema as actually deployed. See migration 013
--       for the patched functions that also update poll_votes.

-- 1) Create the table
create table if not exists public.poll_participants (
  id          bigint generated by default as identity primary key,
  poll_idx    integer                      not null,
  user_id     uuid                         null,
  anon_token  text                         null,
  option_idx  integer                      not null,
  created_at  timestamp with time zone     not null default now(),
  constraint poll_participants_one_identity_check
    check (user_id is not null or anon_token is not null)
);

-- 2) Indexes
create index if not exists idx_poll_participants_poll_idx
  on public.poll_participants (poll_idx);

-- Partial unique indexes prevent duplicates while correctly ignoring NULL values:
--   authenticated users: one vote per (poll, user_id)
create unique index if not exists uq_poll_user
  on public.poll_participants (poll_idx, user_id)
  where user_id is not null;
--   anonymous users: one vote per (poll, anon_token)
create unique index if not exists uq_poll_anon
  on public.poll_participants (poll_idx, anon_token)
  where anon_token is not null;

-- 3) Enable Row Level Security – all access goes through SECURITY DEFINER functions
alter table public.poll_participants enable row level security;

-- ── check_poll_vote ───────────────────────────────────────────────────────────
-- Returns whether the current session has already voted in a given poll.
-- Returns JSON: { "already_voted": true/false }
-- NOTE: Patched in migration 013 to also return option_idx.
create or replace function public.check_poll_vote(
  p_poll_idx   integer,
  p_anon_token text default null
)
returns json
language plpgsql
security definer
as $$
declare
  v_user_id uuid;
  v_exists  boolean;
begin
  v_user_id := auth.uid();

  select exists(
    select 1
    from public.poll_participants
    where poll_idx = p_poll_idx
      and (
        (v_user_id is not null and user_id = v_user_id)
        or
        (v_user_id is null and p_anon_token is not null and anon_token = p_anon_token)
      )
  ) into v_exists;

  return json_build_object('already_voted', v_exists);
end;
$$;

-- ── submit_poll_vote ──────────────────────────────────────────────────────────
-- Accepts an optional anon_token text (generated client-side for anonymous users).
-- For authenticated users, auth.uid() is used automatically.
-- Returns JSON: { "already_voted": true/false, "option_idx": <int> }
-- NOTE: Patched in migration 013 to also increment poll_votes.
create or replace function public.submit_poll_vote(
  p_poll_idx   integer,
  p_option_idx integer,
  p_anon_token text default null
)
returns json
language plpgsql
security definer
as $$
declare
  v_user_id        uuid;
  v_already_voted  boolean := false;
begin
  v_user_id := auth.uid();

  begin
    insert into public.poll_participants (poll_idx, user_id, anon_token, option_idx)
    values (
      p_poll_idx,
      v_user_id,
      case when v_user_id is null then p_anon_token else null end,
      p_option_idx
    );
  exception
    when unique_violation then
      v_already_voted := true;
  end;

  if v_already_voted then
    return json_build_object('already_voted', true, 'option_idx', p_option_idx);
  end if;

  return json_build_object('already_voted', false, 'option_idx', p_option_idx);
end;
$$;

-- Keep the old increment_poll_vote function in place for backwards compatibility.
comment on function increment_poll_vote(smallint, smallint) is
    'Deprecated – use submit_poll_vote() which enforces one vote per participant.';
